
dist: trusty
language: node_js
node_js:
  - stable

env:
 - DATABASE_URL=postgres://postgres:smirk200@localhost:5432/storemanager
script:
  - npm i -g npm@6.1.0
  - p=$(which npm)
  - rm $p
  - ln -s /home/travis/.nvm/versions/node/v10.1.0/bin/npm $p || true
  - npm -v
  - npm run migrate && npm run seed
  - npm test
  - npm install
  - nyc --reporter=lcov npm run test
services:
  - postgresql

before_script:
  - psql -c 'create database storemanager;' -U postgres
  - psql -c "CREATE USER Habib WITH PASSWORD '123456';" -U postgres
after_success: 
  
  - npm run coverage
 